export type Challenge = {
  id: number
  word: string
  tip: string
}

export const WORDS: Challenge[] = [
  { id: 1, word: "CSS", tip: "Linguagem de estilos" },
  { id: 2, word: "REACT", tip: "Biblioteca para criar interfaces Web" },
  { id: 3, word: "HTML", tip: "Linguagem de marcação" },
  { id: 4, word: "Javascript", tip: "Uma das linguagens de programação mais utilizadas no mundo" },
  { id: 5, word: "Typescript", tip: "Para adicionar tipagem no Javascript" },
  { id: 6, word: "Python", tip: "Linguagem conhecida por simplicidade e versatilidade" },
  { id: 7, word: "Java", tip: "Linguagem orientada a objetos multiplataforma (JVM)" },
  { id: 8, word: "C#", tip: "Usada no ecossistema .NET e desenvolvimento de jogos Unity" },
  { id: 9, word: "PHP", tip: "Amplamente utilizada para desenvolvimento web do lado do servidor" },
  { id: 10, word: "Ruby", tip: "Conhecida pelo framework Ruby on Rails e sintaxe elegante" },
  { id: 11, word: "Swift", tip: "Criada pela Apple para desenvolvimento iOS/macOS" },
  { id: 12, word: "Kotlin", tip: "Linguagem moderna para desenvolvimento Android (interopera com Java)" },
  { id: 13, word: "Go", tip: "Linguagem do Google com foco em concorrência e alto desempenho" },
  { id: 14, word: "Rust", tip: "Focada em segurança de memória sem garbage collector" },
  { id: 15, word: "SQL", tip: "Linguagem padrão para gerenciamento de bancos de dados relacionais" },
  { id: 16, word: "NoSQL", tip: "Abordagem de banco de dados não relacional" },
  { id: 17, word: "MongoDB", tip: "Banco de dados NoSQL orientado a documentos" },
  { id: 18, word: "PostgreSQL", tip: "Banco de dados relacional open-source avançado" },
  { id: 19, word: "MySQL", tip: "Sistema de gerenciamento de banco de dados relacional popular" },
  { id: 20, word: "NodeJS", tip: "Ambiente de execução Javascript server-side" },
  { id: 21, word: "Express", tip: "Framework web para Node.js" },
  { id: 22, word: "Django", tip: "Framework Python para desenvolvimento web rápido" },
  { id: 23, word: "Flask", tip: "Microframework Python para aplicações web" },
  { id: 24, word: "Spring", tip: "Framework Java para construção de aplicações empresariais" },
  { id: 25, word: "Angular", tip: "Framework front-end desenvolvido pelo Google" },
  { id: 26, word: "Vue", tip: "Framework JavaScript progressivo para construir interfaces" },
  { id: 27, word: "Svelte", tip: "Framework que compila código para JavaScript puro" },
  { id: 28, word: "NextJS", tip: "Framework React para renderização server-side" },
  { id: 29, word: "NuxtJS", tip: "Framework para construir aplicações Vue.js universais" },
  { id: 30, word: "GraphQL", tip: "Linguagem de consulta para APIs" },
  { id: 31, word: "REST", tip: "Arquitetura para desenvolvimento de APIs web" },
  { id: 32, word: "Docker", tip: "Plataforma para criar, implantar e executar aplicações em containers" },
  { id: 33, word: "Kubernetes", tip: "Sistema de orquestração de containers" },
  { id: 34, word: "Git", tip: "Sistema de controle de versão distribuído" },
  { id: 35, word: "GitHub", tip: "Plataforma de hospedagem de código usando Git" },
  { id: 36, word: "GitLab", tip: "Plataforma DevOps completa baseada em Git" },
  { id: 37, word: "Bitbucket", tip: "Serviço de hospedagem de repositórios Git" },
  { id: 38, word: "JIRA", tip: "Ferramenta de gestão de projetos ágeis" },
  { id: 39, word: "Trello", tip: "Ferramenta de gerenciamento de projetos baseada em quadros" },
  { id: 40, word: "Slack", tip: "Ferramenta de comunicação em equipe" },
  { id: 41, word: "AWS", tip: "Plataforma de computação em nuvem da Amazon" },
  { id: 42, word: "Azure", tip: "Plataforma de nuvem da Microsoft" },
  { id: 43, word: "GCP", tip: "Google Cloud Platform - serviços de nuvem do Google" },
  { id: 44, word: "Firebase", tip: "Plataforma para desenvolvimento de aplicativos móveis e web" },
  { id: 45, word: "Heroku", tip: "Plataforma em nuvem como serviço (PaaS)" },
  { id: 46, word: "Linux", tip: "Sistema operacional open-source baseado em Unix" },
  { id: 47, word: "Ubuntu", tip: "Distribuição popular de Linux" },
  { id: 48, word: "Windows", tip: "Sistema operacional da Microsoft" },
  { id: 49, word: "macOS", tip: "Sistema operacional da Apple para Macs" },
  { id: 50, word: "iOS", tip: "Sistema operacional móvel da Apple" },
  { id: 51, word: "Android", tip: "Sistema operacional móvel do Google" },
  { id: 52, word: "Flutter", tip: "Framework para desenvolvimento de aplicativos móveis multiplataforma" },
  { id: 53, word: "ReactNative", tip: "Framework para construir apps nativos usando React" },
  { id: 54, word: "Xamarin", tip: "Framework para desenvolvimento móvel usando C#" },
  { id: 55, word: "Electron", tip: "Framework para construir aplicações desktop com tecnologias web" },
  { id: 56, word: "Redux", tip: "Biblioteca para gerenciamento de estado em aplicações JavaScript" },
  { id: 57, word: "MobX", tip: "Biblioteca para gerenciamento de estado simples e escalável" },
  { id: 58, word: "Jest", tip: "Framework de testes para JavaScript" },
  { id: 59, word: "Mocha", tip: "Framework de testes para Node.js" },
  { id: 60, word: "Chai", tip: "Biblioteca de asserções para testes em JavaScript" },
  { id: 61, word: "Cypress", tip: "Ferramenta de teste end-to-end para aplicações web" },
  { id: 62, word: "Selenium", tip: "Ferramenta para automação de testes em navegadores" },
  { id: 63, word: "Webpack", tip: "Empacotador de módulos para aplicações JavaScript" },
  { id: 64, word: "Babel", tip: "Transpilador JavaScript para compatibilidade com navegadores" },
  { id: 65, word: "ESLint", tip: "Ferramenta para identificar padrões problemáticos em código JavaScript" },
  { id: 66, word: "Prettier", tip: "Formatador de código opinativo" },
  { id: 67, word: "Sass", tip: "Pré-processador CSS que adiciona recursos avançados" },
  { id: 68, word: "Less", tip: "Pré-processador CSS alternativo ao Sass" },
  { id: 69, word: "Bootstrap", tip: "Framework CSS para desenvolvimento responsivo" },
  { id: 70, word: "Tailwind", tip: "Framework CSS utilitário" },
  { id: 71, word: "MaterialUI", tip: "Biblioteca de componentes React que implementa o Material Design" },
  { id: 72, word: "Figma", tip: "Ferramenta de design de interface baseada na nuvem" },
  { id: 73, word: "Sketch", tip: "Ferramenta de design vetorial para interfaces" },
  { id: 74, word: "AdobeXD", tip: "Ferramenta de design e prototipagem de UX/UI" },
  { id: 75, word: "Photoshop", tip: "Software de edição de imagens da Adobe" },
  { id: 76, word: "Illustrator", tip: "Software de design vetorial da Adobe" },
  { id: 77, word: "TensorFlow", tip: "Biblioteca open-source para machine learning" },
  { id: 78, word: "PyTorch", tip: "Biblioteca de machine learning para Python" },
  { id: 79, word: "ScikitLearn", tip: "Biblioteca de machine learning para Python" },
  { id: 80, word: "Pandas", tip: "Biblioteca Python para análise e manipulação de dados" },
  { id: 81, word: "NumPy", tip: "Biblioteca Python para computação científica" },
  { id: 82, word: "Matplotlib", tip: "Biblioteca Python para visualização de dados" },
  { id: 83, word: "Seaborn", tip: "Biblioteca Python para visualização estatística" },
  { id: 84, word: "D3JS", tip: "Biblioteca JavaScript para visualização de dados" },
  { id: 85, word: "ThreeJS", tip: "Biblioteca JavaScript para gráficos 3D no navegador" },
  { id: 86, word: "Blender", tip: "Software open-source para modelagem 3D" },
  { id: 87, word: "Unity", tip: "Motor de jogo para desenvolvimento 3D e 2D" },
  { id: 88, word: "Unreal", tip: "Motor de jogo avançado desenvolvido pela Epic Games" },
  { id: 89, word: "OOP", tip: "Paradigma de programação baseado em objetos" },
  { id: 90, word: "FP", tip: "Paradigma de programação funcional" },
  { id: 91, word: "API", tip: "Interface de programação de aplicações" },
  { id: 92, word: "CI/CD", tip: "Integração Contínua/Entrega Contínua" },
  { id: 93, word: "DevOps", tip: "Conjunto de práticas que combinam desenvolvimento de software e operações" },
  { id: 94, word: "Agile", tip: "Metodologia ágil de desenvolvimento de software" },
  { id: 95, word: "Scrum", tip: "Framework ágil para gerenciamento de projetos" },
  { id: 96, word: "Kanban", tip: "Método ágil para gestão do trabalho" },
  { id: 97, word: "TDD", tip: "Desenvolvimento guiado por testes" },
  { id: 98, word: "BDD", tip: "Desenvolvimento guiado por comportamento" },
  { id: 99, word: "MVC", tip: "Padrão de arquitetura Model-View-Controller" },
  { id: 100, word: "MVVM", tip: "Padrão de arquitetura Model-View-ViewModel" }

]
